type=item
matchItems=wooden_sword wooden_axe stone_sword stone_axe iron_sword iron_axe copper_sword copper_axe golden_sword golden_axe diamond_sword diamond_axe netherite_sword netherite_axe mace
model=./axe_of_voided_divination.json
texture=./axe_of_voided_divination.png
texture.emissive=./axe_of_voided_divination_e.png
