type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword trident
model=./hornet_needle.json
texture=./hornet_needle.png
nbt.display.Name=ipattern:*needle of fate*