type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=./mythra_aegis.json
texture=./mythra_aegis.png
texture.emissive=./mythra_aegis_e.png
components.minecraft\:custom_name=ipattern:*The Blade of Gleaming Light*
# components.minecraft\:enchantments/levels/minecraft:sharpness=3:5
weight=10