type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=./mythra_aegis.json
texture=./mythra_aegis.png
texture.emissive=./mythra_aegis_e.png
nbt.display.Name=ipattern:*The Blade of Gleaming Light*
# nbt.Enchantments.*.id=minecraft:sharpness
# nbt.Enchantments.*.lvl=3:5
weight=10