# type=item
# matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
# model=./mythra_aegis_d.json
# texture=./mythra_aegis.png
# texture.emissive=./mythra_aegis_e.png
# nbt.display.Name=ipattern:*The Blade of Gleaming Light*
# weight=5