type=item
items=bow
model=./staff_of_voided_divination.json
texture.bow_standby=./staff_of_voided_divination.png
texture.bow_pulling_0=./staff_of_voided_divination_0.png
texture.bow_pulling_1=./staff_of_voided_divination_1.png
texture.bow_pulling_2=./staff_of_voided_divination_2.png
texture.emissive=./staff_of_voided_divination_e.png
components.minecraft\:custom_name=ipattern:*Staff of Voided Divination*