type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=./master_sword.json
texture=./master_sword.png
nbt.display.Name=ipattern:*The Sword that Seals the Darkness*
texture.emissive=./master_sword_e.png