type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=./dream_nail.json
texture=./dream_nail.png
components.minecraft\:custom_name=ipattern:*Nail of Dreams*