type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword wooden_axe stone_axe iron_axe golden_axe diamond_axe netherite_axe
model=./pyra_aegis.json
texture=./pyra_aegis.png
texture.emissive=./pyra_aegis_e.png
nbt.display.Name=ipattern:*The Blade of Searing Flame*