type=item
matchItems=iron_sword wooden_sword stone_sword diamond_sword golden_sword iron_axe wooden_axe stone_axe diamond_axe golden_axe netherite_sword netherite_axe
components.minecraft\:custom_name=ipattern:*Blade of Gales*
model=./windcleaver.json
texture=./windcleaver.png
texture.emissive=./windcleaver_e.png