type=item
matchItems= wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=./azurelight.json
texture=./azurelight.png
texture.emissive=./azurelight_e.png
nbt.display.Name=ipattern:*Azurelight*