type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword wooden_axe stone_axe iron_axe golden_axe diamond_axe netherite_axe
model=./voidblade.json
texture=./voidblade.png
texture.emissive=./voidblade_e.png
nbt.display.Name=ipattern:*The Blade of Gilded Void*