type=item
matchItems=totem_of_undying
model=./lightkeepers_oath.json
texture=./lightkeepers_oath.png
texture.emissive=./lightkeepers_oath_e.png
components.minecraft\:custom_name=ipattern:*Lightkeeper's Oath*